apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: aksdemo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: aksdemo-app
    spec:
      containers:
        - name: aksdemo-services-app
          image: aksdemoregi.azurecr.io/aksdemo:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
    name: aksdemo-app
spec:
  ports:
    - name: http-port
      port: 80
      targetPort: 80
  selector:
    app: aksdemo-app
  type: LoadBalancer