apiVersion: apps/v1
kind: Deployment
metadata:
  name: aksdemo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: aksdemo-app
  template:
    metadata:
      labels:
        app: aksdemo-app
    spec:
      containers:
        - name: aksdemo-services-app
          image: ssaz400cr.azurecr.io/ssgs-ems:latest
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "250m"
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
    name: aksdemo-app
spec:
  ports:
    - name: http-port
      port: 80
      targetPort: 80
  selector:
    app: aksdemo-app
  type: LoadBalancer
